manifest-version = 1

[component]
name = "plausible"
version = "1.0.2"
category = "data-collection"
subcategory = "analytics"
repository = "https://github.com/edgee-cloud/plausible-component"
documentation = "https://www.edgee.cloud/docs/components/data-collection/plausible"
description = '''
## Overview

The **Plausible Analytics** component by Edgee enables seamless integration of Plausible Analytics into your Edgee projects.
This component allows you to collect and forward analytics events to your Plausible instance, providing lightweight and privacy-friendly web analytics without the need for embedding additional scripts on your site.

---

## Key Features & Benefits

### Features

- **Edge Deployment**: Collect analytics at the edge for faster page loads, lower latency, and smoother user experiences.
- **Privacy-First**: Fully GDPR, CCPA, and PECR compliant, ensuring safe and responsible data collection.
- **Lightweight & Fast**: Optimized by Edgee, the script stays minimal, keeping pages fast without sacrificing analytics.
- **Seamless Integration**: Connects effortlessly with other Edgee components for complete end-to-end data workflows.

### Benefits

- **Faster Load Times**: Enhanced user experience with better performance.
- **Regulation Compliance**: Simplified alignment with privacy laws and frameworks.
- **Fewer Dependencies**: Reduced reliance on third-party scripts.
- **Simple Setup**: Easy integration into existing Edgee workflows.

---

## Use Cases

- **Privacy-Compliant Analytics**: Collect and analyze user data without compromising privacy.
- **Performance Optimization**: Offload analytics processing to the edge to improve website performance.
- **Open-Source Solutions**: Utilize an open-source analytics tool that aligns with your organization's values.
- **Simplified Integration**: Integrate analytics into your project without the need for complex setups or embedding external scripts.

---

Additional resources: [Plausible Analytics Documentation](https://plausible.io/docs)
'''
language = "Rust"
icon-path = "icon.png"
wit-version = "1.0.0"

[component.build]
command = "cargo build --target wasm32-wasip2 --release && rm -f plausible.wasm && cp ./target/wasm32-wasip2/release/plausible_edgee_component.wasm plausible.wasm"
output_path = "plausible.wasm"

[component.settings.domain]
title = "Site domain"
type = "string"
required = true
description = "Domain name of the site in Plausible"

[component.settings.instance_url]
title = "Custom instance URL"
type = "string"
description = "Base URL of your self-hosted Plausible instance"
