manifest-version = 1

[component]
name = "plausible"
version = "0.1.3"
category = "data-collection"
subcategory = "analytics"
language = "Rust"
icon-path = "icon.png"
wit-version = "1.0.0"

[component.build]
command = "cargo build --target wasm32-wasip2 --release"
output_path = "target/wasm32-wasip2/release/plausible_edgee_component.wasm"

[component.settings.instance_url]
title = "Instance URL"
type = "string"
required = true
description = "Base URL of your Plausible instance (e.g. \"https://plausible.io\")"
default = "https://plausible.io"

[component.settings.domain]
title = "Site domain"
type = "string"
required = true
description = "Domain name of the site in Plausible"
