manifest-version = 1

[component]
name = "plausible"
version = "1.0.0"
category = "data-collection"
subcategory = "analytics"
repository = "https://github.com/edgee-cloud/plausible-component"
description = '''
This component enables seamless integration between [Edgee](https://www.edgee.cloud) and [Plausible](https://plausible.io),
allowing you to collect and forward analytics events to your Plausible instance.
'''
language = "Rust"
icon-path = "icon.png"
wit-version = "1.0.0"

[component.build]
command = "cargo build --target wasm32-wasip2 --release && cp ./target/wasm32-wasip2/release/plausible_edgee_component.wasm plausible.wasm"
output_path = "plausible.wasm"

[component.settings.domain]
title = "Site domain"
type = "string"
required = true
description = "Domain name of the site in Plausible"

[component.settings.instance_url]
title = "Custom instance URL"
type = "string"
description = "Base URL of your self-hosted Plausible instance"
